services:
  smtp:
    image: rnwood/smtp4dev:latest
    restart: always
    ports:
      - "81:80"
    volumes:
      - smtpdb:/smtp4dev

  expiro:
    build: ./
    restart: always
    ports: 
      - "80:5050"
    environment:
      - GIN_MODE=debug
      - EXPIRO_LOGGING_ENABLED=true
      - EXPIRO_LOGGING_FILE=logs/expiro.log
      - EXPIRO_ENGINE=sqlite
      - EXPIRO_SQLITE_FILEPATH=data/expiro.db
      - EXPIRO_NOTIFICATION_SMTP_HOST=smtp
      - EXPIRO_NOTIFICATION_FROMADDRESS=expiro@yourdomain.com
    volumes:
      - expirologs:/app/logs
      - expirodb:/app/data
    links:
      - smtp

volumes:
  expirodb: {}
  expirologs: {}
  smtpdb: {}
  