sonar.projectKey=Isotop7_proviant
sonar.organization=isotop7-1

sonar.projectName=proviant

sonar.sources=src
sonar.exclusions=\
    **/vendor/**,\
    **/node_modules/**,\
    **/*.gen.go,\
    **/docs/**,\
    **/assets/**,\
    **/*.min.js,\
    **/design-system/**

sonar.tests=src
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=src/coverage.out

sonar.sourceEncoding=UTF-8
